# Day 08

https://adventofcode.com/2022/day/8

## Part 1

In [1]:
import numpy as np

In [2]:
test_result = 21
test_data = """\
30373
25512
65332
33549
35390"""
test_data

'30373\n25512\n65332\n33549\n35390'

In [3]:
test_data.splitlines()

['30373', '25512', '65332', '33549', '35390']

In [4]:
def import_data(data):
    map_data = []
    for line in data.splitlines():
        map_data.append([int(x) for x in line])
    map_data = np.array(map_data, dtype=int)
    return map_data

print(import_data(test_data))

[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]


In [5]:
def solution1(data, verbose=False):
    map_data = import_data(data)
    
    # trees on edge
    h, w = map_data.shape
    sol1 = 2 * (h + w) - 4
    print("trees on edge:", sol1)
    
    for row in range(1, map_data.shape[0]-1):
        for col in range(1, map_data.shape[1]-1):
            cur_val = map_data[row, col]
            left = map_data[row, :][:col]
            right = map_data[row, :][col+1:]
            above = map_data[:, col][:row]
            below = map_data[:, col][row+1:]

            if verbose:
                print(cur_val, left, right, above, below)
            if cur_val > left.max():
                sol1 += 1         
                if verbose:
                    print("visible from left")
                continue
            elif cur_val > right.max():
                sol1 += 1            
                if verbose:
                    print("visible from right")
                continue
            elif cur_val > above.max():
                sol1 += 1            
                if verbose:
                    print("visible from above")
                continue
            elif cur_val > below.max():
                sol1 += 1
                if verbose:
                    print("visible from below")
                continue
            
    print("result:", sol1)
    return sol1

assert solution1(test_data) == test_result

print("test passed")

trees on edge: 16
result: 21
test passed


In [6]:
with open("day08.txt") as f:
    inp_data = f.read()
sol1 = solution1(inp_data)

assert sol1 < 2541
assert sol1 == 1825
print("test passed")

trees on edge: 392
result: 1825
test passed


## Part 2

In [7]:
test_result = 8

In [8]:
def solution2(data):
    sol2 = 0
    map_data = import_data(data)

    h, w = map_data.shape

    for row in range(1, map_data.shape[0]-1):
        for col in range(1, map_data.shape[1]-1):
            cur_val = map_data[row, col]
            left = 0
            for i in range(col-1, -1, -1):
                left += 1            
                if not map_data[row, i] < cur_val:
                    break
            right = 0
            for i in range(col+1, w):
                right += 1
                if not map_data[row, i] < cur_val:
                    break
            above = 0
            for i in range(row-1, -1, -1):
                above += 1
                if not map_data[i, col] < cur_val:
                    break
            below = 0
            for i in range(row+1, h):
                below += 1
                if not map_data[i, col] < cur_val:
                    break
            score = left * right * above * below
            #print((row, col,), (left, right, above, below), score)
            sol2 = max(sol2, score)
    print("result:", sol2)
    return sol2

assert solution2(test_data) == test_result
print("test passed")

result: 8
test passed


In [9]:
sol2 = solution2(inp_data)
assert sol2 < 483516
assert sol2 == 235200
print("test passed")

result: 235200
test passed
